### ISSUE TITLE
Algunas mejoras

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-3-evaluacion-intermedia-romerogarcia#1]
Buen trabajo @romerogarcia  !

### Algunas pistas para acabarlo:

- [x] Como sugerencia general, comprueba continuamente tu aplicación en Chrome y el terminal dónde arrancas la app con `npm start`. Si algo falla, hay que arreglarlo antes de continuar.
- [x] Pon un `<label>` para indicar para qué es cada `<input>` y recuerda asociarlos con el atributo `htmlFor`.
- [x] Continúa implementando los filtros para texto que esté en la frase y personaje.
- [x] Verifica el filtro de personajes, de manera que incluya si la usuaria ha seleccionado todos
- [ ] Comprueba que los `inputs` tengan algún valor cuando vas a añadir una nueva frase. 
- [x] Elimina el código comentado, debuggers y consoles
- [x] Haz los bonus del ejercicio para que sigas practicando! 

> Recuerda: a medida que vayas realizando estas mejoras debes subirlas a la rama principal de este repo y marcarlas como realizadas en este issue. Si no, tu profe no sabrás que has realizado estas mejoras.

Si tienes cualquier duda, ¡avisa!

Al turrón!!!

**Comment by romerogarcia** [comment]
Mejoras realizadas!

**Comment by igarrido-adalab** [comment]
Ok, perfecto!
